version: "3"
services:
    gorm-test-clickhouse:
      image: clickhouse/clickhouse-server:latest
      container_name: gorm-test-clickhouse
      environment:
        - CLICKHOUSE_DB=gorm
        - CLICKHOUSE_USER=gorm
        - CLICKHOUSE_PASSWORD=gorm
      ports:
      - "9941:8123"
      - "9942:9000"
      - "9943:9009"
